experiment:
  name: eval_multiscale_ckpt_on_text8
  seed: 42

device: auto
cuda_device: 0

data:
  dataset: text8
  data_dir: data/text8
  block_size: 512
  train_ratio: 0.99999
  sampling: sequential
  steps_per_epoch: 1000

loader:
  batch_size: 128
  num_workers: 16

model:
  backbone: multiscale_mamba2_lm
  d_model: 256
  layer_headdims: [32, 32, 32, 32]
  vocab_size: 0
  multiscale:
    stride: 4
    fusion: gated
    fast_layer_headdims: [32, 32, 32, 32]
    slow_layer_headdims: [32, 32]
  mamba:
    d_state: 32
    d_conv: 4
    expand: 2
    ngroups: 1

eval:
  checkpoint_path: /home/jovyan/shares/SR008.fs2/nvidenisov/other/repos/mamba/mamba_multi_scale_get_started/outputs/TinyShakespeare/tiny_shakespeare_multiscale_mamba2_ctx512/best.pt
  vocab_path: null
  evaluate_train: false

logging:
  output_dir: outputs/EvalLM/${experiment.name}
